# -*- coding: utf-8 -*-
"""ML-Exercise-5.8.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gx6KIfpwsIKIxuUsV33oj92LGZpKd9SA
"""

# Import necessary libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Sample dataset from the image
data = {
    'Weight': [79, 69, 73, 95, 82, 55, 69, 71, 64, 69],
    'Height': [1.80, 1.68, 1.82, 1.70, 1.87, 1.55, 1.50, 1.78, 1.67, 1.64],
    'Age': [35, 39, 25, 60, 27, 18, 89, 42, 16, 52],
    'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female']
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Encode the 'Gender' column
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])  # Male = 1, Female = 0

# Define independent variables (X) and target variable (y)
X = df[['Height', 'Age', 'Gender']]
y = df['Weight']

# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluation
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

# Show coefficients
print("\nModel Coefficients:")
print(f"Height: {model.coef_[0]:.2f}")
print(f"Age: {model.coef_[1]:.2f}")
print(f"Gender: {model.coef_[2]:.2f}")
print(f"Intercept: {model.intercept_:.2f}")